#Persistent Volume MYSQL
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-mysql-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/drupal-mysql-data"
    
#Persistent Volume Drupal
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-pv
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/drupal-data"